tags:
  discounts-green: false
  products-green: false

global:
  namespace: test
  #needed for rollouts analysis
  prometheusAddress: https://prometheus-user-workload.openshift-user-workload-monitoring.svc.cluster.local:9091

discounts-blue:
  mode: online
  quarkus-base:
    fullnameOverride: "discounts"
    image:
      tag: v1.0.1
    version: none
    rollouts:
      enabled: true
      analysis:
        web: true
        service: "discounts-umbrella-offline"
      blueGreen:
        enabled: true
        activeService: "discounts-umbrella-online"
        previewService: "discounts-umbrella-offline"
  fullnameOverride: "discounts"
  
products-blue:
  mode: online
  quarkus-base:
    image:
      tag: v1.1.1
    replicaCount: 2
    fullnameOverride: "products"
    version: none
    rollouts:
      enabled: true
      analysis:
        web: true
        service: "products-umbrella-online"
      blueGreen:
        enabled: true
        activeService: "products-umbrella-online"
        previewService: "products-umbrella-offline"
  fullnameOverride: "products"









